dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install --upgrade keyring==21.4.0 setuptools wheel twine
  - pip install coveralls tox
# command to run tests
script:
  - tox
  - if [[ `python --version` =~ 3.7 ]]; then coveralls; fi
  - tox -e integration
  - python setup.py sdist bdist_wheel
  - twine check dist/*
