# encoding: utf-8
from typing import Any, Dict, Iterator, AsyncIterator, Optional, Generator
from .item import AsyncItem, Item, camel, snake


from abc import abstractmethod

class GetMixIn:
    @abstractmethod
    def __iter__(self) -> Iterator[Any]: ...

    def get(self, name: str) -> Any:
        return next((item for item in self if item.name == name), None)


class ResultBase:

    def __init__(self, raw):
        self.raw = raw

    def __getattr__(self, name):
        camel_name = camel(name)
        if camel_name in self.raw:
            return self.raw[camel_name]
        return super().__getattribute__(name)

    def __str__(self):
        return f'<{type(self).__name__}: {self.name}>'

    def __dir__(self) -> list[str]:
        return list(super().__dir__()) + [snake(k) for k in self.raw]


class TestReport(Item, GetMixIn):

    def __iter__(self) -> Iterator['TestSuite']:
        for suite in self.api_json()['suites']:
            yield TestSuite(suite)

    @property
    def suites(self) -> Generator['TestSuite', None, None]:
        yield from self


class TestSuite(ResultBase, GetMixIn):

    def __iter__(self) -> Iterator['TestCase']:
        for case in self.raw['cases']:
            yield TestCase(case)

    @property
    def cases(self) -> Generator['TestCase', None, None]:
        yield from self


class TestCase(ResultBase):
    pass


class CoverageReport(Item, GetMixIn):
    '''Access coverage report generated by `JaCoCo <https://plugins.jenkins.io/jacoco/>`_'''

    report_types = ['branchCoverage', 'classCoverage', 'complexityScore',
                    'instructionCoverage', 'lineCoverage', 'methodCoverage']

    def __getattr__(self, name: str) -> Any:
        attr = camel(name)
        if attr not in self.report_types:
            raise AttributeError(
                f"'CoverageReport' object has no attribute '{name}'")
        return self.get(attr)

    def __iter__(self) -> Iterator['Coverage']:
        for k, v in self.api_json().items():
            if k not in ['_class', 'previousResult']:
                v['name'] = k
                yield Coverage(v)

    def trends(self, count: int = 2) -> Generator['Coverage', None, None]:
        def _resolve(data: Dict[str, Any]) -> Generator['Coverage', None, None]:
            if data['previousResult']:
                yield from _resolve(data['previousResult'])
            for k, v in data.items():
                if k not in ['_class', 'previousResult']:
                    v['name'] = k
                    yield Coverage(v)

        yield from _resolve(self.api_json(depth=count))


class Coverage(ResultBase):
    pass


class CoverageResult(Item, GetMixIn):
    '''Access coverage result generated by `Code Coverage API <https://plugins.jenkins.io/code-coverage-api/>`_'''

    def __iter__(self):
        for element in self.api_json(depth=1)['results']['elements']:
            yield CoverageElement(element)


class CoverageElement(ResultBase):
    pass


class CoverageTrends(Item, GetMixIn):
    def __iter__(self) -> Iterator['CoverageTrend']:
        for trend in self.api_json(depth=1)['trends']:
            trend['name'] = trend['buildName']
            yield CoverageTrend(trend)


class CoverageTrend(ResultBase):

    def __iter__(self) -> Iterator['CoverageElement']:
        for element in self.raw['elements']:
            yield CoverageElement(element)


# async class

from collections.abc import AsyncIterator

from typing import Protocol

class AsyncIterableMixIn(Protocol):
    @abstractmethod 
    async def __aiter__(self) -> AsyncIterator[Any]: ...

from typing import TypeVar, Generic, overload
from typing_extensions import Self

T = TypeVar('T')

from collections.abc import AsyncIterator
from typing import TypeVar, Generic
from typing_extensions import Self

T = TypeVar('T')

from typing import TypeVar, Generic
from collections.abc import AsyncIterator
from typing_extensions import Protocol

T = TypeVar('T')

from typing import TypeVar, Generic
from collections.abc import AsyncIterator
from typing_extensions import Protocol

T = TypeVar('T')

from typing import TypeVar, Generic
from collections.abc import AsyncIterator

T = TypeVar('T')

from typing import TypeVar, Generic
from collections.abc import AsyncIterator
from typing_extensions import Protocol

T = TypeVar('T')

from typing import TypeVar, Generic
from collections.abc import AsyncIterator

T = TypeVar('T')

class AsyncGetMixIn(Generic[T]):
    """
    Base class providing async iteration and item lookup functionality.
    
    Note: Uses async generators which may show type checking limitations in Pylance.
    The implementation is correct and works at runtime despite type checker warnings.
    """
    
    @abstractmethod
    async def __aiter__(self) -> AsyncIterator[T]:  # type: ignore[override]
        """Async iterator method to be implemented by subclasses."""
        ...

    async def get(self, name: str) -> T:
        """Get an item by name from the async iterable."""
        async for item in self:
            if item.name == name:
                return item
        raise ValueError(f"Item with name '{name}' not found")


class AsyncTestReport(AsyncItem, AsyncGetMixIn[TestSuite]):
    async def __aiter__(self) -> AsyncIterator[TestSuite]:  # type: ignore[override]
        """Iterate over test suites in the report."""
        data = await self.api_json()
        for suite in data['suites']:
            yield TestSuite(suite)

    @property
    async def suites(self) -> AsyncIterator[TestSuite]:
        async for suite in self:
            yield suite


class AsyncCoverageReport(AsyncItem, AsyncGetMixIn):
    '''Access coverage report generated by `JaCoCo <https://plugins.jenkins.io/jacoco/>`_'''

    report_types = ['branchCoverage', 'classCoverage', 'complexityScore',
                    'instructionCoverage', 'lineCoverage', 'methodCoverage']

    async def __getattr__(self, name):
        attr = camel(name)
        if attr not in self.report_types:
            raise AttributeError(
                f"'CoverageReport' object has no attribute '{name}'")
        return await self.get(attr)

    async def __aiter__(self) -> AsyncIterator[Coverage]:  # type: ignore[override]
        data = await self.api_json()
        for k, v in data.items():
            if k not in ['_class', 'previousResult']:
                v['name'] = k
                yield Coverage(v)

    async def trends(self, count: int = 2) -> AsyncIterator[Coverage]:
        async def _resolve(data: Dict[str, Any]) -> AsyncIterator[Coverage]:
            if data['previousResult']:
                async for item in _resolve(data['previousResult']):
                    yield item
            for k, v in data.items():
                if k not in ['_class', 'previousResult']:
                    v['name'] = k
                    yield Coverage(v)
        data = await self.api_json(depth=count)
        async for c in _resolve(data):
            yield c


class AsyncCoverageResult(AsyncItem, AsyncGetMixIn):
    '''Access coverage result generated by `Code Coverage API <https://plugins.jenkins.io/code-coverage-api/>`_'''

    async def __aiter__(self) -> AsyncIterator[CoverageElement]:  # type: ignore[override]
        data = await self.api_json(depth=1)
        for element in data['results']['elements']:
            yield CoverageElement(element)


class AsyncCoverageTrends(AsyncItem, AsyncGetMixIn):
    async def __aiter__(self) -> AsyncIterator[CoverageTrend]:  # type: ignore[override]
        data = await self.api_json(depth=1)
        for trend in data['trends']:
            trend['name'] = trend['buildName']
            yield CoverageTrend(trend)
